import { MarkerType } from "@xyflow/react"

export const nodes = [
  {
    id: "1",
    position: { x: 10, y: 100 },
    data: { label: "Алликсаар" },
    type: "custom",
  },
  {
    id: "2",
    position: { x: 800, y: 100 },
    data: { label: "Ду Хаст Вячеславович" },
    type: "custom",
  },
  {
    id: "3",
    position: { x: 170, y: 250 },
    data: { label: "Станислав Клитотехнис" },
    type: "custom",
  },
  {
    id: "4",
    position: { x: 320, y: 320 },
    data: { label: "Людмила Водолазская" },
    type: "custom",
  },
  {
    id: "5",
    position: { x: 320, y: 390 },
    data: { label: "Ольга Боргдорф" },
    type: "custom",
  },
  {
    id: "6",
    position: { x: 320, y: 600 },
    data: { label: "Сергей Брус" },
    type: "custom",
  },
  {
    id: "7",
    position: { x: 170, y: 670 },
    data: { label: "Игорь Зверёк" },
    type: "custom",
  },
  {
    id: "8",
    position: { x: 170, y: 740 },
    data: { label: "Антон Строй" },
    type: "custom",
  },
  {
    id: "9",
    position: { x: 800, y: 170 },
    data: { label: "Анастасия Ширинкина" },
    type: "custom",
  },
  {
    id: "10",
    position: { x: 800, y: 250 },
    data: { label: "Александр Троян" },
    type: "custom",
  },
  {
    id: "11",
    position: { x: 800, y: 390 },
    data: { label: "Дмитрий Возигнуй" },
    type: "custom",
  },
  {
    id: "12",
    position: { x: 800, y: 460 },
    data: { label: "Кристина Болтушкина" },
    type: "custom",
  },
  {
    id: "13",
    position: { x: 800, y: 530 },
    data: { label: "Максим Висюлькин" },
    type: "custom",
  },
]

const edgeParams = { type: "step", markerEnd: { type: MarkerType.Arrow } }

export const edges = [
  {
    id: "e2-1",
    source: "2",
    target: "1",
    sourceHandle: "source-left",
    targetHandle: "target-right",
    ...edgeParams,
  },
  {
    id: "e9-1",
    source: "9",
    target: "1",
    sourceHandle: "source-left",
    targetHandle: "target-right",
    ...edgeParams,
  },
  {
    id: "e10-3",
    source: "10",
    target: "3",
    sourceHandle: "source-left",
    targetHandle: "target-right",
    ...edgeParams,
  },
  {
    id: "e3-1",
    source: "3",
    target: "1",
    sourceHandle: "source-left",
    targetHandle: "target-bottom",
    ...edgeParams,
  },
  {
    id: "e4-3",
    source: "4",
    target: "3",
    sourceHandle: "source-left",
    targetHandle: "target-bottom",
    ...edgeParams,
  },
  {
    id: "e5-3",
    source: "5",
    target: "3",
    sourceHandle: "source-left",
    targetHandle: "target-bottom",
    ...edgeParams,
  },
  {
    id: "e6-3",
    source: "6",
    target: "3",
    sourceHandle: "source-left",
    targetHandle: "target-bottom",
    ...edgeParams,
  },
  {
    id: "e7-1",
    source: "7",
    target: "1",
    sourceHandle: "source-left",
    targetHandle: "target-bottom",
    ...edgeParams,
  },
  {
    id: "e8-1",
    source: "8",
    target: "1",
    sourceHandle: "source-left",
    targetHandle: "target-bottom",
    ...edgeParams,
  },
  {
    id: "e11-5",
    source: "11",
    target: "5",
    sourceHandle: "source-left",
    targetHandle: "target-right",
    ...edgeParams,
  },
  {
    id: "e12-5",
    source: "12",
    target: "5",
    sourceHandle: "source-left",
    targetHandle: "target-right",
    ...edgeParams,
  },
  {
    id: "e13-5",
    source: "13",
    target: "5",
    sourceHandle: "source-left",
    targetHandle: "target-right",
    ...edgeParams,
  },
  {
    id: "e13-11",
    source: "13",
    target: "11",
    sourceHandle: "source-right",
    targetHandle: "target-right",
    ...edgeParams,
  },
]
